#!/usr/bin/env python3
"""Regenerate seed_questions.sql from BANK in js/questions.js.

Run from anywhere after editing BANK:
    python3 supabase/generate_seed.py

That rewrites the full seed (used for a fresh Supabase project). For a
project that already has rows, do NOT re-run the whole seed — append only
the new questions, keeping per-category order, e.g. with append_questions.py.
Per-category order must match the hardcoded BANK exactly, or the daily
question diverges between an online phone (DB copy) and an offline one.
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATS = ["funny", "romantic", "spicy", "nasty", "ldr", "deep",
        "dareapart", "dareapartx", "daretogether", "daretogetherx", "filthy"]


def load_bank():
    """Parse BANK out of js/questions.js -> {category: [question, ...]}."""
    src = open(os.path.join(ROOT, "js", "questions.js"), encoding="utf-8").read()
    start = src.index("const BANK = {")
    block = src[start:src.index("\n};", start)]
    bank = {}
    for cat in CATS:
        seg = block[block.index(cat + ": ["):]
        seg = seg[:seg.index("\n  ]")]
        qs = [json.loads(m) for m in re.findall(r'"(?:[^"\\]|\\.)*"', seg)]
        assert qs, "no questions found for category " + cat
        bank[cat] = qs
    return bank


def sql_values(bank):
    rows = []
    for cat in CATS:
        rows += ["  ('%s', '%s')" % (cat, q.replace("'", "''")) for q in bank[cat]]
    return rows


if __name__ == "__main__":
    bank = load_bank()
    rows = sql_values(bank)
    out = (
        "-- Seed the questions table from the app's built-in BANK.\n"
        "-- Generated by generate_seed.py -- per-category order must match the\n"
        "-- hardcoded BANK exactly, or the shared daily pick diverges from\n"
        "-- offline phones.\n\n"
        "insert into questions (category, text) values\n" + ",\n".join(rows) + ";\n"
    )
    open(os.path.join(ROOT, "supabase", "seed_questions.sql"), "w", encoding="utf-8").write(out)
    print({c: len(bank[c]) for c in CATS}, "| total", len(rows))
