#!/usr/bin/env python3
"""Regenerate seed_questions.sql from BANK in index.html.

Run from the repo root (or this directory) after editing BANK:
    python3 supabase/generate_seed.py
Then re-apply in the Supabase SQL editor:
    delete from questions;  -- then paste the fresh seed_questions.sql

Per-category order must match the hardcoded BANK exactly, or the shared
daily question diverges between online (DB) and offline (fallback) phones.
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATS = ["funny", "romantic", "spicy", "nasty", "ldr"]

src = open(os.path.join(ROOT, "index.html"), encoding="utf-8").read()
block = src[src.index("const BANK = {"):src.index("};", src.index("const BANK = {"))]

rows = []
counts = {}
for cat in CATS:
    seg = block[block.index(cat + ": ["):]
    seg = seg[:seg.index("]")]
    qs = [json.loads(m) for m in re.findall(r'"(?:[^"\\]|\\.)*"', seg)]
    assert qs, "no questions found for category " + cat
    counts[cat] = len(qs)
    rows += ["  ('%s', '%s')" % (cat, q.replace("'", "''")) for q in qs]

out = (
    "-- Seed the questions table from the app's built-in BANK.\n"
    "-- Generated by generate_seed.py -- per-category order must match the\n"
    "-- hardcoded BANK exactly, or the shared daily pick diverges from\n"
    "-- offline phones.\n\n"
    "insert into questions (category, text) values\n" + ",\n".join(rows) + ";\n"
)
open(os.path.join(ROOT, "supabase", "seed_questions.sql"), "w", encoding="utf-8").write(out)
print(counts, "| total", len(rows))
