-- Seed the questions table from the app's built-in BANK.
-- Generated from index.html -- per-category order must match the hardcoded
-- BANK exactly, or the shared daily pick diverges from offline phones.

insert into questions (category, text) values
  ('funny', 'If I were a kitchen appliance, which one would I be — and why?'),
  ('funny', 'What''s the weirdest thing you''ve caught me doing when I thought no one was watching?'),
  ('funny', 'If we got arrested together, what would it 100% be for?'),
  ('funny', 'Which animal do I turn into when I''m hangry?'),
  ('funny', 'What would the title of a reality show about us be?'),
  ('funny', 'If my snoring was a music genre, which one would it be?'),
  ('funny', 'What''s one word or phrase I say WAY too much?'),
  ('funny', 'If we swapped bodies for a day, what''s the first thing you''d do?'),
  ('funny', 'What is my most useless talent?'),
  ('funny', 'If our love story was a movie, which actor would play me? Be honest.'),
  ('funny', 'What smell instantly reminds you of me? Be nice… or don''t.'),
  ('funny', 'If I was an ice cream flavor, what would I be called?'),
  ('funny', 'What''s the dumbest argument we''ve ever had?'),
  ('funny', 'Which emoji best describes my dance moves?'),
  ('funny', 'If aliens abducted us both, who would they return first — and why?'),
  ('funny', 'What is my villain origin story?'),
  ('funny', 'If our couple had a mascot, what would it be?'),
  ('funny', 'What ridiculous thing would I buy first if we won the lottery?'),
  ('funny', 'Which cartoon character is basically me?'),
  ('funny', 'What''s the funniest face I make, and when do I make it?'),
  ('funny', 'If my brain had a loading screen, what would it say?'),
  ('funny', 'What conspiracy theory could you convince me of by Friday?'),
  ('funny', 'What would I go viral on the internet for — for all the wrong reasons?'),
  ('funny', 'If we opened a terrible restaurant together, what would it be called?'),
  ('funny', 'What''s one chore I do so badly you suspect it''s on purpose?'),
  ('funny', 'Who would survive longer in a zombie apocalypse — and defend your answer?'),
  ('funny', 'What''s the weirdest compliment you could give me right now?'),
  ('funny', 'If I came with a warning label, what would it say?'),
  ('funny', 'What theme song should play every time I walk into a room?'),
  ('funny', 'What''s probably the most embarrassing thing in my search history?'),
  ('funny', 'If we were a crime duo, who''s the brains and who''s the one who gets us caught?'),
  ('funny', 'What''s a hill I would absolutely die on for no good reason?'),
  ('funny', 'If I had to be haunted by a ghost, what kind of ghost would annoy me the most?'),
  ('funny', 'What do you think I was like at age seven?'),
  ('funny', 'Which household object understands me on a spiritual level?'),
  ('romantic', 'What was the exact moment you knew you were falling for me?'),
  ('romantic', 'What''s your favorite memory of us that you secretly replay in your head?'),
  ('romantic', 'What little thing do I do that makes you feel the most loved?'),
  ('romantic', 'Where in the world would you want to wake up next to me tomorrow?'),
  ('romantic', 'What''s one thing about my smile you''ve never told me?'),
  ('romantic', 'If you could relive one of our dates exactly as it happened, which one?'),
  ('romantic', 'What song feels like ''us'' to you?'),
  ('romantic', 'What do you look forward to most about growing old together?'),
  ('romantic', 'When do you find me most attractive — when I''m not even trying?'),
  ('romantic', 'What tiny detail about me did you notice the very first time we met?'),
  ('romantic', 'How did you describe me to your friends when we first started dating?'),
  ('romantic', 'What''s your favorite way I say ''I love you'' without actually saying it?'),
  ('romantic', 'If we renewed our vows tomorrow, what''s one line you''d include?'),
  ('romantic', 'What future memory with me are you most excited to make?'),
  ('romantic', 'What''s one thing I''ve taught you about love?'),
  ('romantic', 'Which of my quirks did you fall for first?'),
  ('romantic', 'What does ''home'' feel like when you think of me?'),
  ('romantic', 'What''s the most romantic thing I''ve done without realizing it was romantic?'),
  ('romantic', 'If our love had a color, what would it be and why?'),
  ('romantic', 'What do you want us to be doing exactly 10 years from today?'),
  ('romantic', 'When did you last catch yourself just staring at me?'),
  ('romantic', 'Which dream of mine do you secretly root for the hardest?'),
  ('romantic', 'What part of our story would you never, ever change?'),
  ('romantic', 'What''s a promise you want to make me today?'),
  ('romantic', 'What''s your favorite photo of us, and why that one?'),
  ('romantic', 'What''s something small I did this week that made your heart squeeze?'),
  ('romantic', 'If you wrote me a love letter right now, what would the first line be?'),
  ('romantic', 'What''s a place we''ve never been that you want to fall in love with together?'),
  ('romantic', 'What did you think our first kiss would be like — and how was the real one better?'),
  ('romantic', 'What''s one thing you hope we still do together when we''re 80?'),
  ('spicy', 'What am I wearing when you find me completely irresistible?'),
  ('spicy', 'What''s one kiss from me you still think about?'),
  ('spicy', 'Describe our best kiss ever in exactly three words.'),
  ('spicy', 'Where''s the most adventurous place you''d want to make out with me?'),
  ('spicy', 'What''s your favorite way I touch you?'),
  ('spicy', 'What''s one thing I do in public that secretly drives you a little crazy?'),
  ('spicy', 'If tonight had no rules, how would you want it to start?'),
  ('spicy', 'Which outfit of mine would you like to see more often… on the floor?'),
  ('spicy', 'What''s a fantasy date night you''ve never told me about?'),
  ('spicy', 'Slow dance in the dark or a shower together — pick one for tonight.'),
  ('spicy', 'What compliment about your body do you never get tired of hearing from me?'),
  ('spicy', 'What''s the most attractive thing I do without even noticing?'),
  ('spicy', 'A whisper in your ear or a text under the table — how should I flirt with you when we''re out?'),
  ('spicy', 'What''s one thing you want more of from me this week? Kisses count.'),
  ('spicy', 'Which is more dangerous: morning cuddles that go too far, or midnight ones?'),
  ('spicy', 'Where is my most kissable spot? Point to it later.'),
  ('spicy', 'If I planned a surprise ''date'' that starts at 10pm, what should I include?'),
  ('spicy', 'What''s one small thing I could do tonight that would completely ruin your concentration?'),
  ('spicy', 'Which memory of us do you think about when you miss me the most… physically?'),
  ('spicy', 'Rate my flirting game from 1–10, then show me how it''s done.'),
  ('spicy', 'What''s the first thing you noticed about my body?'),
  ('spicy', 'If we had a whole rainy Sunday in bed, what''s on the agenda?'),
  ('spicy', 'What''s something I wear that you consider a personal attack (in the best way)?'),
  ('spicy', 'Kissing my neck or holding my waist — which one do you enjoy more?'),
  ('spicy', 'What look do I give you that you can read instantly?'),
  ('nasty', 'What''s one thing you''ve always wanted to try with me but never said out loud?'),
  ('nasty', 'What''s your favorite spot in our home… and be honest about why.'),
  ('nasty', 'If we had a ''yes night'' — neither of us can say no to a request — what''s your first request?'),
  ('nasty', 'What''s something I do in bed that you''d like on repeat?'),
  ('nasty', 'Truth: have you ever thought about me at a VERY inappropriate time? When?'),
  ('nasty', 'We have the place to ourselves for exactly one hour, starting now. Go.'),
  ('nasty', 'Lights on or lights off — and defend your answer.'),
  ('nasty', 'What''s the naughtiest thought you''ve had about me this week?'),
  ('nasty', 'What should our code word be for ''we''re leaving this party immediately''?'),
  ('nasty', 'Which of my texts has ever made you blush in public?'),
  ('nasty', 'What''s one rule we should break tonight?'),
  ('nasty', 'Set the scene perfectly: music, lighting, outfit. What are you picking?'),
  ('nasty', 'What''s something new you want to try this month? I''m taking notes.'),
  ('nasty', 'A massage that starts innocent, or a kiss that doesn''t — choose your opening move.'),
  ('nasty', 'What''s the hottest thing I''ve ever said to you? Quote it if you dare.'),
  ('nasty', 'Where should my hands be right now, hypothetically speaking?'),
  ('nasty', 'What''s your favorite ''view'' of me?'),
  ('nasty', 'If we''d just met tonight, how would you seduce me?'),
  ('nasty', 'What''s one text I could send tomorrow that would completely derail your day?'),
  ('nasty', 'Describe tonight''s plans in exactly five words. Make them count.'),
  ('nasty', 'What time of day am I at my most dangerous?'),
  ('nasty', 'What''s one thing I underestimate about my own effect on you?'),
  ('nasty', 'Pick a movie scene you''d want to reenact with me — any genre.'),
  ('nasty', 'What am I better at than I realize? Be specific.'),
  ('nasty', 'Finish this sentence: ''Tonight, I want you to…'''),
  ('ldr', 'What''s the FIRST thing we''re doing when we''re in the same room again?'),
  ('ldr', 'If you could teleport to me for just 10 minutes right now, what would we do?'),
  ('ldr', 'What do you miss most about me today? Pick exactly one thing.'),
  ('ldr', 'Virtual date night: synced movie, cooking the same dinner, or online games — pick tonight''s.'),
  ('ldr', 'What song do you play when you miss me?'),
  ('ldr', 'What''s the hardest part of your day without me — and the easiest?'),
  ('ldr', 'If I mailed you a care package tomorrow, what MUST be in it?'),
  ('ldr', 'What''s one thing you want to show me in your city next time I visit?'),
  ('ldr', 'Describe your day today like a dramatic movie trailer.'),
  ('ldr', 'What photo of us did you look at most recently?'),
  ('ldr', 'When we reunite, are we more likely to cry, laugh, or make everyone at the airport uncomfortable?'),
  ('ldr', 'What''s something you''re saving to tell me in person instead of over text?'),
  ('ldr', 'Voice message or video call — what does your heart need tonight?'),
  ('ldr', 'What do you hold or sleep with that reminds you of me? Be honest.'),
  ('ldr', 'Plan our next visit in exactly 3 emojis. The other has to guess the itinerary.'),
  ('ldr', 'What''s one habit of mine you weirdly miss?'),
  ('ldr', 'What''s your favorite message I''ve ever sent you? Scroll back and quote it.'),
  ('ldr', 'If the distance were a video game boss, what''s today''s difficulty rating and why?'),
  ('ldr', 'What are we eating first when we''re together again?'),
  ('ldr', 'What''s one thing this distance has taught you about us?');
