// questions.js — Lucia ♥ Riu
// The prompt bank (offline fallback for the Supabase `questions` table),
// category chips, and the deterministic Question of the Day dealt to the
// home page. The Talk · Flirt · Dare tab draws from the same bank — see
// js/tfd.js.

// ---------------- QUESTION BANK ----------------
const BANK = {
  funny: [
    "If I were a kitchen appliance, which one would I be — and why?",
    "What's the weirdest thing you've caught me doing when I thought no one was watching?",
    "If we got arrested together, what would it 100% be for?",
    "Which animal do I turn into when I'm hangry?",
    "What would the title of a reality show about us be?",
    "If my snoring was a music genre, which one would it be?",
    "What's one word or phrase I say WAY too much?",
    "If we swapped bodies for a day, what's the first thing you'd do?",
    "What is my most useless talent?",
    "If our love story was a movie, which actor would play me? Be honest.",
    "What smell instantly reminds you of me? Be nice… or don't.",
    "If I was an ice cream flavor, what would I be called?",
    "What's the dumbest argument we've ever had?",
    "Which emoji best describes my dance moves?",
    "If aliens abducted us both, who would they return first — and why?",
    "What is my villain origin story?",
    "If our couple had a mascot, what would it be?",
    "What ridiculous thing would I buy first if we won the lottery?",
    "Which cartoon character is basically me?",
    "What's the funniest face I make, and when do I make it?",
    "If my brain had a loading screen, what would it say?",
    "What conspiracy theory could you convince me of by Friday?",
    "What would I go viral on the internet for — for all the wrong reasons?",
    "If we opened a terrible restaurant together, what would it be called?",
    "What's one chore I do so badly you suspect it's on purpose?",
    "Who would survive longer in a zombie apocalypse — and defend your answer?",
    "What's the weirdest compliment you could give me right now?",
    "If I came with a warning label, what would it say?",
    "What theme song should play every time I walk into a room?",
    "What's probably the most embarrassing thing in my search history?",
    "If we were a crime duo, who's the brains and who's the one who gets us caught?",
    "What's a hill I would absolutely die on for no good reason?",
    "If I had to be haunted by a ghost, what kind of ghost would annoy me the most?",
    "What do you think I was like at age seven?",
    "Which household object understands me on a spiritual level?",
    "What's the most unhinged thing I'd do for free food?",
    "If I hosted a podcast, what would it be about and who would actually listen?",
    "What's my most embarrassing main-character moment?",
    "Describe my sense of style as a newspaper headline.",
    "Which of my habits would make a dangerous drinking game?",
    "What's the pettiest thing I've ever been genuinely upset about?",
    "If I ran for office, what's my campaign slogan — and my inevitable scandal?",
    "Which chore do I treat like an Olympic event?",
    "If my life had subtitles, what would they say when I'm hungry?",
    "What's the worst gift someone could give me, and how badly would I fake loving it?"
  ],
  romantic: [
    "What was the exact moment you knew you were falling for me?",
    "What's your favorite memory of us that you secretly replay in your head?",
    "What little thing do I do that makes you feel the most loved?",
    "Where in the world would you want to wake up next to me tomorrow?",
    "What's one thing about my smile you've never told me?",
    "If you could relive one of our dates exactly as it happened, which one?",
    "What song feels like 'us' to you?",
    "What do you look forward to most about growing old together?",
    "When do you find me most attractive — when I'm not even trying?",
    "What tiny detail about me did you notice the very first time we met?",
    "How did you describe me to your friends when we first started dating?",
    "What's your favorite way I say 'I love you' without actually saying it?",
    "If we renewed our vows tomorrow, what's one line you'd include?",
    "What future memory with me are you most excited to make?",
    "What's one thing I've taught you about love?",
    "Which of my quirks did you fall for first?",
    "What does 'home' feel like when you think of me?",
    "What's the most romantic thing I've done without realizing it was romantic?",
    "If our love had a color, what would it be and why?",
    "What do you want us to be doing exactly 10 years from today?",
    "When did you last catch yourself just staring at me?",
    "Which dream of mine do you secretly root for the hardest?",
    "What part of our story would you never, ever change?",
    "What's a promise you want to make me today?",
    "What's your favorite photo of us, and why that one?",
    "What's something small I did this week that made your heart squeeze?",
    "If you wrote me a love letter right now, what would the first line be?",
    "What's a place we've never been that you want to fall in love with together?",
    "What did you think our first kiss would be like — and how was the real one better?",
    "What's one thing you hope we still do together when we're 80?",
    "What's something ordinary that stopped feeling ordinary once we did it together?",
    "When did you last feel proud to be with me?",
    "What part of my personality do you hope never changes?",
    "If you could keep only one photo of us forever, which one?",
    "What do you hope I know about how you feel, even on the days we don't say it?",
    "When have you felt safest with me?",
    "What's a small ritual of ours you'd miss most if it disappeared?",
    "What has loving me taught you about yourself?",
    "If today were a chapter in our story, what would you title it?",
    "What's the moment you'd replay from us if you only got one?"
  ],
  spicy: [
    "What am I wearing when you find me completely irresistible?",
    "What's one kiss from me you still think about?",
    "Describe our best kiss ever in exactly three words.",
    "Where's the most adventurous place you'd want to make out with me?",
    "What's your favorite way I touch you?",
    "What's one thing I do in public that secretly drives you a little crazy?",
    "If tonight had no rules, how would you want it to start?",
    "Which outfit of mine would you like to see more often… on the floor?",
    "What's a fantasy date night you've never told me about?",
    "Slow dance in the dark or a shower together — pick one for tonight.",
    "What compliment about your body do you never get tired of hearing from me?",
    "What's the most attractive thing I do without even noticing?",
    "A whisper in your ear or a text under the table — how should I flirt with you when we're out?",
    "What's one thing you want more of from me this week? Kisses count.",
    "Which is more dangerous: morning cuddles that go too far, or midnight ones?",
    "Where is my most kissable spot? Point to it later.",
    "If I planned a surprise 'date' that starts at 10pm, what should I include?",
    "What's one small thing I could do tonight that would completely ruin your concentration?",
    "Which memory of us do you think about when you miss me the most… physically?",
    "Rate my flirting game from 1–10, then show me how it's done.",
    "What's the first thing you noticed about my body?",
    "If we had a whole rainy Sunday in bed, what's on the agenda?",
    "What's something I wear that you consider a personal attack (in the best way)?",
    "Kissing my neck or holding my waist — which one do you enjoy more?",
    "What look do I give you that you can read instantly?",
    "What's the last thing I did that made you look twice?",
    "If I could only touch you in one place tonight, where should it be?",
    "What's something I own that you've never admitted you love seeing me in?",
    "Do you want my hands or my full attention right now? Choose.",
    "What look do I give you that changes the mood instantly?",
    "Twenty minutes and a locked door — what happens first?",
    "What do I say that sounds completely innocent to everyone but you?",
    "Where do you want to be kissed that I haven't kissed you yet?",
    "What's your favorite thing I do in the second before we kiss?",
    "If I sent you one photo right now, what should be in it?"
  ],
  nasty: [
    "What's one thing you've always wanted to try with me but never said out loud?",
    "What's your favorite spot in our home… and be honest about why.",
    "If we had a 'yes night' — neither of us can say no to a request — what's your first request?",
    "What's something I do in bed that you'd like on repeat?",
    "Truth: have you ever thought about me at a VERY inappropriate time? When?",
    "We have the place to ourselves for exactly one hour, starting now. Go.",
    "Lights on or lights off — and defend your answer.",
    "What's the naughtiest thought you've had about me this week?",
    "What should our code word be for 'we're leaving this party immediately'?",
    "Which of my texts has ever made you blush in public?",
    "What's one rule we should break tonight?",
    "Set the scene perfectly: music, lighting, outfit. What are you picking?",
    "What's something new you want to try this month? I'm taking notes.",
    "A massage that starts innocent, or a kiss that doesn't — choose your opening move.",
    "What's the hottest thing I've ever said to you? Quote it if you dare.",
    "Where should my hands be right now, hypothetically speaking?",
    "What's your favorite 'view' of me?",
    "If we'd just met tonight, how would you seduce me?",
    "What's one text I could send tomorrow that would completely derail your day?",
    "Describe tonight's plans in exactly five words. Make them count.",
    "What time of day am I at my most dangerous?",
    "What's one thing I underestimate about my own effect on you?",
    "Pick a movie scene you'd want to reenact with me — any genre.",
    "What am I better at than I realize? Be specific.",
    "Finish this sentence: 'Tonight, I want you to…'",
    "What's a thought about us you'd only confess at 2am?",
    "If tonight were entirely your plan, what's the itinerary?",
    "What's the boldest thing you'd whisper to me in a crowded room?",
    "What's one thing you want me to do slower?",
    "Name a place we absolutely shouldn't — but you've thought about it.",
    "What's the hottest part of watching me lose control?",
    "One rule for tonight: what is it, and who breaks it first?",
    "What do you think about when you can't sleep and I'm not there?",
    "What's something you want me to ask you for?",
    "Finish this: 'Next time I see you, I'm not letting you…'"
  ],
  ldr: [
    "What's the FIRST thing we're doing when we're in the same room again?",
    "If you could teleport to me for just 10 minutes right now, what would we do?",
    "What do you miss most about me today? Pick exactly one thing.",
    "Virtual date night: synced movie, cooking the same dinner, or online games — pick tonight's.",
    "What song do you play when you miss me?",
    "What's the hardest part of your day without me — and the easiest?",
    "If I mailed you a care package tomorrow, what MUST be in it?",
    "What's one thing you want to show me in your city next time I visit?",
    "Describe your day today like a dramatic movie trailer.",
    "What photo of us did you look at most recently?",
    "When we reunite, are we more likely to cry, laugh, or make everyone at the airport uncomfortable?",
    "What's something you're saving to tell me in person instead of over text?",
    "Voice message or video call — what does your heart need tonight?",
    "What do you hold or sleep with that reminds you of me? Be honest.",
    "Plan our next visit in exactly 3 emojis. The other has to guess the itinerary.",
    "What's one habit of mine you weirdly miss?",
    "What's your favorite message I've ever sent you? Scroll back and quote it.",
    "If the distance were a video game boss, what's today's difficulty rating and why?",
    "What are we eating first when we're together again?",
    "What's one thing this distance has taught you about us?",
    "What's the first text you'll send me the morning we wake up in the same city?",
    "Which of our video calls do you still think about?",
    "What do you do on the days the distance feels heaviest?",
    "What could I mail you that would fix an entire bad week?",
    "If we could share one sense across the distance — touch, smell, or hearing — which?",
    "What plan do we keep calling 'someday' that we should actually book?",
    "Which part of your daily routine would change most if I were there?",
    "What's the best thing about missing me? There has to be one.",
    "Which of my voice messages would you save forever?",
    "When we finally live in the same place, what's the first boring Tuesday night we spend together?"
  ],
  deep: [
    "What's a belief you held five years ago that you've completely let go of?",
    "What are you most afraid of losing — and have you ever said it out loud?",
    "When do you feel most like yourself?",
    "What are you still trying to forgive yourself for?",
    "What did your childhood teach you about love that you've had to unlearn?",
    "Describe a good life ten years from now, in detail.",
    "What's a fear about us you've never told me?",
    "Which of your parents do you see in yourself, and how do you feel about that?",
    "What do you need more of that you've never asked me for?",
    "When did you last change your mind about something that mattered?",
    "What part of yourself do you hide from most people, but not from me?",
    "What would you do with your life if money and other people's opinions didn't exist?",
    "What's the hardest thing you've survived, and who were you afterward?",
    "Is home a place, a person, or a feeling to you?",
    "What do you want people to say about you when you're not in the room?",
    "What's a dream you quietly gave up on? Should you have?",
    "How do you know when you can trust someone?",
    "What are you proud of that nobody ever congratulates you for?",
    "Where are you still growing, and where do you feel stuck?",
    "What's the kindest thing anyone has ever done for you?",
    "Honestly — what do you think we'd argue about in ten years?",
    "What boundary do you wish you were better at holding?",
    "When did you last cry, and what was it really about?",
    "What does success mean to you now versus at twenty?",
    "What's one thing about your future that genuinely scares you?",
    "Who do you owe an apology to — yourself included?",
    "What do you need from me when you're struggling that I don't always give you?",
    "What memory shaped you more than people would guess?",
    "If we get fifty years together, what would make you say it was worth it?",
    "What's true about you that takes people a long time to see?"
  ],
  dareapart: [
    "Send me a photo of whatever's in front of you right now. No tidying up first.",
    "Voice-note me the song that's stuck in your head — singing it, obviously.",
    "Change your lock screen to a photo of us and send proof.",
    "Write me a one-star review of my worst habit, like I'm a product.",
    "Send a selfie making the face you make when I say something ridiculous.",
    "Describe my laugh in a voice note. Cruelty permitted.",
    "Show me the 7th most recent photo in your camera roll. No context, no excuses.",
    "Set a reminder to text me something filthy at a random time tomorrow.",
    "Photograph the last thing you ate and rate it as if I cooked it.",
    "Tell me your entire day in emojis only — I have to guess it back.",
    "Send me a picture of the view out your nearest window right now.",
    "Text me a compliment you've thought about me but never said out loud.",
    "Give me a video tour of your fridge, narrated like a nature documentary.",
    "Send me your battery percentage and a promise the size of that number.",
    "Write a two-line poem about the distance. It is allowed to be terrible.",
    "Photograph something in your room that reminds you of me.",
    "Voice-note me your honest ranking of my three best qualities.",
    "Draw me from memory in thirty seconds and send it. No do-overs.",
    "Send a song that's exactly how you feel right now. No explanation allowed.",
    "Tell me something you've never told anyone — as a voice note, so I hear it.",
    "Plan one small thing for future-us and text me what it is.",
    "Take a photo of your hand and tell me where you'd put it if I were there.",
    "Send the ugliest selfie you are physically capable of producing. I'll frame it.",
    "Change my contact name to something embarrassing for 24 hours. Screenshot it.",
    "Tell me about your day but lie about one detail — I have to catch it.",
    "Text me one thing you want us to do on our next trip.",
    "Mirror selfie, right now, however you look. Excuses are not accepted.",
    "Send me a photo of your hands doing whatever they're doing right now.",
    "Say 'I miss you' in the most dramatic accent you can manage. Record it.",
    "Send me a photo of your current chaos: desk, bag, or floor. Dealer's choice."
  ],
  dareapartx: [
    "Send me a photo of what you're wearing. Then send one with less.",
    "Voice-note the exact thing you'd whisper if you were on top of me.",
    "Text me where you want my mouth. Be specific.",
    "Send a photo from the angle you know undoes me.",
    "Tell me what you did the last time you thought about me alone.",
    "Text me the filthiest sentence you're willing to type. Autocorrect is no defence.",
    "Set tonight's alarm label to what you want me to do to you. Screenshot it.",
    "Send me a photo of your lips, then tell me where they'd go.",
    "Tell me one thing you've imagined but never dared ask me for.",
    "Ten seconds of you saying my name the way you'd say it at 2am.",
    "Photograph the empty side of your bed and tell me what I'd be doing in it.",
    "Describe the first five minutes after we get a door that locks. Skip nothing.",
    "Wear something of mine to bed tonight and send proof.",
    "Send a photo that shows nothing and promises everything.",
    "Name the moment today you thought about me and absolutely shouldn't have.",
    "Voice-note the three things happening the second I'm through your door.",
    "Send me a photo of your neck and your instructions for it.",
    "Text me one sentence that will ruin my concentration for the rest of the day.",
    "Describe what you're wearing to bed in unnecessary, unhurried detail.",
    "Tell me the rule you want broken next time we're alone. Then tell me again, slower.",
    "Type out, step by step, exactly how tonight would go if I were there.",
    "Record yourself breathing for ten seconds. That's the whole dare.",
    "Send me your favourite photo of my body and tell me precisely why it's that one.",
    "Leave me a voicemail I'd have to delete before anyone else could hear it.",
    "Tell me what you're doing right now — and then what you'd rather be doing to me."
  ],
  daretogether: [
    "Kiss me somewhere you've never kissed me. Ten seconds to decide.",
    "Thirty-second massage. Anywhere you like.",
    "Whisper what you want tonight, in exactly five words.",
    "Sit on my lap until you've named three things you love about me.",
    "Feed me the next thing you eat.",
    "Take a photo of us right now, however we look.",
    "Slow dance with me to whatever's playing. Nothing playing? Hum.",
    "Hold eye contact for one full minute. First to laugh loses.",
    "Trace a word on my back with your finger — I have to guess it.",
    "Kiss me the way you did the first time. Recreate it exactly.",
    "Steal my hoodie and wear it for the rest of the night.",
    "Best pickup line you've got. Out loud, straight face.",
    "Do my hair however you want. I'm not allowed to look until you're done.",
    "Pick my outfit for tomorrow. I'm wearing it, no appeals.",
    "Compliment me while looking me in the eyes. No jokes allowed.",
    "Sit close enough that no light gets between us, for one whole song.",
    "Bite my shoulder. Gently. Or don't — your call.",
    "Take my hand and put it where you want it.",
    "Kiss me for as long as it takes you to get through the alphabet.",
    "Hug me until one of us gets restless. It had better not be you.",
    "Tell me what you want to do to me later — in my ear, so only I hear it.",
    "Cover my eyes with your hand and kiss me somewhere I won't expect.",
    "Undo one thing. Your choice what.",
    "Straddle me and tell me about your day as though nothing is happening.",
    "Two-minute timer. Make out until it goes off — ignoring it is permitted."
  ],
  daretogetherx: [
    "Take something off. You choose what; I choose where it lands.",
    "Kiss your way down from my neck until I tell you to stop. I won't.",
    "Put my hand exactly where you want it and hold it there.",
    "Tell me what you want out loud, in filthy detail. Then I'll decide.",
    "Get on top and don't let me move for two minutes.",
    "Undress me using your teeth wherever that's physically possible.",
    "Whisper the dirtiest thing you've thought about me this week, in my ear.",
    "Show me exactly how you touch yourself when you're thinking about me.",
    "Ten minutes, no hands for you. I make the rules.",
    "Pin me down and tell me what happens next.",
    "Bite me somewhere that'll still be there tomorrow.",
    "Take me to the least sensible room in this place.",
    "Say my name the way you say it when you're close.",
    "Do that thing you did last time. You know the one. Slower.",
    "Beg for something. Be specific.",
    "Cover my eyes and use only your mouth for five minutes.",
    "Tell me to do something to you. I'm not allowed to say no.",
    "Kiss me like you've been waiting 1,800 miles for it. Because you have.",
    "Take a photo of me right now that we can never show anyone.",
    "Sit on the edge and let me kneel.",
    "Leave a mark somewhere only the two of us will ever see.",
    "Make me stop talking. Your method, your choice.",
    "Hands above your head. Don't move them until I say.",
    "Describe what you want me to do — then let me do the opposite, slower.",
    "Show me what you'd do if we had five minutes and a locked door.",

    // +100 (2026-08-01) — appended at the END so the DB and BANK stay in the
    // same order; see supabase/append_questions.py.
    "Set a timer for five minutes. I can't touch you until it goes.",
    "Choose: my mouth or my hands. You only get one for ten minutes.",
    "Take my hand and show me your pace. I'll match it exactly.",
    "Tell me to stop. I will. Then tell me when to start again.",
    "Blindfold me with whatever's nearest and lead me somewhere.",
    "Undo one button at a time. I have to hold eye contact throughout.",
    "You're in charge for ten minutes. Say it out loud first.",
    "Kiss me once, properly, then walk off and make me follow.",
    "Sit still. Whatever I do, don't move a muscle. Try.",
    "Read me something filthy off your phone. Your pick.",
    "No talking for five minutes. Show me instead.",
    "Pick something of mine you want gone. Remove it slowly.",
    "Push me against the nearest wall and take your time.",
    "Ask me for it. Properly. In a full sentence.",
    "Trace where you want my mouth. I'll follow the line exactly.",
    "Hold my wrists and tell me what you're about to do.",
    "One kiss, thirty seconds, neither of us allowed hands.",
    "Lights off. Find me by touch alone.",
    "Tell me the thing you've never asked for. I'm saying yes.",
    "Count to twenty out loud. I'll be busy. Don't lose it.",
    "Take my shirt off without letting it touch the floor.",
    "Tell me more or less, out loud, every thirty seconds.",
    "Pin my hands and kiss me until I stop trying to move.",
    "Pick a room we've never done anything in. Go there now.",
    "Give me one instruction. I'll follow it to the letter.",
    "Slow everything down by half. Yes, that slow. Keep going.",
    "Kiss the last place I'd expect. Take your time getting there.",
    "Say what you want me to say. I'll say it in your ear.",
    "Two minutes of nothing but your mouth on my neck. Timed.",
    "Put my hand where you want it, then let go and see.",
    "Undress each other at once. First one finished decides what's next.",
    "Set a rule for tonight. I'm not allowed to break it.",
    "Make me ask for it twice. Enjoy the first one.",
    "Do the thing you know I can't sit still through.",
    "Straddle me and don't let me sit up.",
    "Fingertips only for three minutes. Nothing else.",
    "Whisper what you want done to you, then let me improvise.",
    "Don't look away. Whatever happens.",
    "Take my hands and use them on yourself.",
    "Wear only the thing I hand you. Wait there.",
    "Bite my lip hard enough that I remember it tomorrow.",
    "Tell me what you thought about on the flight here.",
    "Take everything off except one thing. Your choice which.",
    "Kneel. Don't ask what for.",
    "Kiss me until one of us gives in. It won't be me.",
    "Set a rule I have to obey for fifteen minutes.",
    "Get me out of breath without either of us undressing.",
    "Hold still while I take my time. No helping.",
    "Tell me exactly how you want to be touched. Then correct me.",
    "Use your mouth to answer the next thing I ask.",
    "Take my hand and lead me where you were thinking about earlier.",
    "Do it again. Then again. Don't change a thing.",
    "Undo my belt with one hand. One attempt.",
    "Show me your favourite thing we've ever done. Now.",
    "No touching for two minutes. Just tell me what you'd do.",
    "Lie back and let me do all of it. Not a finger from you.",
    "Ask me to beg. I'll think about it.",
    "Say the thing you only say with the lights off.",
    "Take my hair in your hand and tell me what you want.",
    "Kiss me somewhere that'll make me swear.",
    "Ten seconds to get me on the bed. Starting now.",
    "Choose the music, then match its pace exactly.",
    "Tell me I can't. Then watch.",
    "One slow line down me. One finger. That's all.",
    "Photograph the mark you left. That one stays ours.",
    "Get me to say please. Then make me say it again.",
    "One item off each, every time either of us laughs.",
    "Hold my face still and don't let me look away.",
    "Take the long way. Skip nothing.",
    "Tell me the fantasy you've never said out loud. All of it.",
    "Do to me exactly what I did to you last time.",
    "Hands behind your back. Manage anyway.",
    "Whisper a countdown from ten. I'll try to make you lose it.",
    "Choose: I go slow and you can't touch me, or the reverse.",
    "Put your hand over my mouth and carry on.",
    "Undress me facing the mirror so I have to watch.",
    "Tell me where to be at midnight. I'll be there.",
    "Make me wait a full minute longer than I want to.",
    "Say my name three times. Make each one mean something different.",
    "Take off whatever I'm most attached to right now.",
    "Kiss every place you missed. Say them out loud as you go.",
    "Let me undress you without using my hands.",
    "Push me down and take exactly what you want.",
    "Tell me to stay still. Then make it impossible.",
    "Five minutes. My mouth. Your rules. Go.",
    "Put my hand somewhere that'll shut me up.",
    "Show me what you were thinking about on our last call.",
    "Leave a mark I'll find in the shower tomorrow.",
    "The slowest possible version of what you want. Nothing faster.",
    "Ask permission for everything for ten minutes.",
    "Take the lead and don't hand it back.",
    "Whisper what happens after this. Then do it.",
    "Only kissing for ten minutes. Nothing else. I mean it.",
    "Make me forget we spent the last month on FaceTime.",
    "Tell me how long you've wanted this. Then stop talking.",
    "Whatever happens next, you're not allowed to be quiet.",
    "Name the thing you want most tonight. Then wait for it.",
    "Take my hand off you and put it back somewhere better.",
    "Undress me in the order I'd least expect.",
    "Say it filthier. I didn't catch that."
  ],
  filthy: [
    "What's the filthiest thought you've had about me in public?",
    "Where do you want my mouth first?",
    "What do you want me to do to you that you've never said out loud?",
    "How should I wake you the first morning we share a bed again?",
    "What's the hottest thing I've ever done to you? Details, please.",
    "What do you think about when you're alone and thinking about me?",
    "Rough or slow tonight — and why that one?",
    "What's one thing you'd rather be told than asked?",
    "What would you want me to do if you couldn't use your hands?",
    "Where's the least appropriate place you've wanted me?",
    "What's a sound I make that you replay later?",
    "What do you want more of that you've been too polite to ask for?",
    "If you could keep me in one position all night, which?",
    "What's the first thing you'd take off me?",
    "Which part of my body do you most want in your hands?",
    "What should happen the second we're alone — before either of us talks?",
    "What do you want me wearing when you arrive? Be specific.",
    "What have we done once that you want to become a habit?",
    "Do you want to be in charge tonight, or do you want me to be?",
    "What's the dirtiest thing you'd let me whisper to you in a crowded room?",
    "What's your favourite thing to hear me say when we're alone?",
    "What would you never say sober but absolutely mean?",
    "Where do you want to be marked?",
    "What's the fantasy you're saving to tell me in person?",
    "What's the one thing that would end me fastest, and do you know it?"
  ]
};


const CHIPS = {
  funny:    { label: "😂 Funny",    color: "#ffd166" },
  romantic: { label: "💕 Romantic", color: "#ff7aa2" },
  spicy:    { label: "🌶️ Spicy",   color: "#ff6b4a" },
  nasty:    { label: "😈 After Dark", color: "#ff2e63" },
  ldr:      { label: "💌 Long Distance", color: "#7ac7ff" },
  deep:     { label: "🧠 Deep", color: "#a99bff" },
  dareapart:     { label: "✈️ Dare", color: "#ff9f45" },
  dareapartx:    { label: "😈 Dare", color: "#ff2e63" },
  daretogether:  { label: "💞 Dare", color: "#ff9f45" },
  daretogetherx: { label: "😈 Dare", color: "#ff2e63" },
  filthy:        { label: "🔥 Filthy", color: "#ff2e63" }
};

// The hardcoded BANK is the offline fallback; once Supabase answers,
// loadQuestions() swaps this for the DB copy (identical content, so the
// deck deals the same card either way).
let QUESTION_SOURCE = BANK;

// Home's Question of the Day stays sweet on purpose — spicy, deep and dare
// live behind a deliberate tap in the Talk · Flirt · Dare tab (js/tfd.js).
const QOTD_CATS = ["funny", "romantic", "ldr"];

function flatOf(cats) {
  const out = [];
  cats.forEach(c => (QUESTION_SOURCE[c] || []).forEach(q => out.push({ cat: c, text: q })));
  return out;
}

function styleChip(el, cat) {
  const chip = CHIPS[cat];
  if (!el || !chip) return;
  el.textContent = chip.label;
  el.style.borderColor = chip.color;
  el.style.background = chip.color + "33";
}

// ---------------- THE DAILY DECK ----------------
// Deal a deck instead of drawing blind each day.
//
// The original version seeded the PRNG per day and took a single draw, so a
// day could land on the same question as the day before (~5 times a year)
// while other questions went unseen for years — that's the birthday problem,
// not a broken PRNG. Now the whole pool is shuffled once per cycle and dealt
// in order: every question appears exactly once before any of them repeats.
// Still seeded, so both phones deal the identical deck with no server.
function shuffledOrder(n, seed) {
  const rng = mulberry32(seed);
  const order = Array.from({ length: n }, (_, i) => i);
  for (let i = n - 1; i > 0; i--) { // Fisher–Yates
    const j = Math.floor(rng() * (i + 1));
    const tmp = order[i]; order[i] = order[j]; order[j] = tmp;
  }
  return order;
}

// The finished deck for one pass. The anti-repeat swap has to be baked in
// here, for every day of the cycle — applying it only on the boundary day
// would deal the swapped card twice (day 0 and again on day 1).
function deckForCycle(n, cycle, offset) {
  const order = shuffledOrder(n, offset + cycle * 7919);
  // a fresh deck must not open on the card the previous one closed with.
  // Safe to read the previous deck unswapped: the swap only ever touches
  // positions 0 and 1, never the last card (n > 2).
  if (cycle > 0 && n > 2) {
    const prev = shuffledOrder(n, offset + (cycle - 1) * 7919);
    if (prev[n - 1] === order[0]) { const t = order[0]; order[0] = order[1]; order[1] = t; }
  }
  return order;
}

// Same date ⇒ same question on both phones, and it never changes on refresh.
function dailyQuestion() {
  const pool = flatOf(QOTD_CATS);
  const n = pool.length;
  if (!n) return { cat: "funny", text: "Our question bank is empty — that's a bug 😅" };
  const day = Math.max(0, dayNumber() - 1);
  return pool[deckForCycle(n, Math.floor(day / n), 0)[day % n]];
}
